# Generated by Django 4.0.5 on 2023-05-19 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('inventory', '0002_alter_inventorymodel_options_and_more'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newstockmodel',
            options={'verbose_name_plural': 'Nhập kho'},
        ),
        migrations.AlterField(
            model_name='newstockmodel',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày'),
        ),
        migrations.AlterField(
            model_name='newstockmodel',
            name='order_no',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Mã'),
        ),
        migrations.AlterField(
            model_name='newstockmodel',
            name='price',
            field=models.IntegerField(verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='newstockmodel',
            name='quantity',
            field=models.IntegerField(verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='newstockmodel',
            name='sku',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventorymodel', verbose_name='Sản phẩm'),
        ),
        migrations.AlterField(
            model_name='newstockmodel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.suppliermodel', verbose_name='Nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='newstockmodel',
            name='total_price',
            field=models.IntegerField(verbose_name='Tổng giá'),
        ),
    ]
