# Generated by Django 4.0.5 on 2023-05-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorymodel',
            options={'verbose_name_plural': 'Kho'},
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='available_quantity',
            field=models.IntegerField(verbose_name='Hiện còn'),
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='sku',
            field=models.CharField(max_length=100, verbose_name='Sản phẩm'),
        ),
    ]
